### ISSUE TITLE
Getting `403` Error for androidStoreURL in checkVersion()

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [watanabeyu/react-native-store-version#34] opened 2022-03-25 19:31 UTC
I am using `react-native-store-version` to check the version of my application on the play store:

```
           import checkVersion from 'react-native-store-version';

           const check = await checkVersion({
                version: currentAppVersion, // app local version
                iosStoreURL: 'https://apps.apple.com/us/app/servr/id1473118642?ls=1',
                androidStoreURL: 'https://play.google.com/store/apps/details?id=com.servr',
                country: 'pk', // default value is 'jp'
            });
```

But I am getting the following error `403 Forbidden` on `androidStoreURL`

![image](https://user-images.githubusercontent.com/41861952/160188807-9b6a3d8a-55be-4fd5-8acc-380ed0ea1eeb.png)

**Comment by antoniovuono** [comment] 2022-05-26 13:32
I got the same problem. With IOS, sound good. But android, I got the same issue.

**Comment by atulsharmaTFT** [comment] 2022-05-27 08:36
Hi, 
We are also facing the same issue .. for ios its working fine but for android its not working 
<img width="502" alt="Screenshot 2022-05-27 at 2 05 26 PM" src="https://user-images.githubusercontent.com/94036900/170663238-99418641-8b6c-4d12-8408-14412a274cc8.png">

**Comment by Zerolink2099** [comment] 2022-05-31 21:13
The error is caused by google play's new layout of the app`s page. 

_diff --git a/node_modules/react-native-store-version/dist/android.js b/node_modules/react-native-store-version/dist/android.js
index 469615f..ad10a8f 100644
--- a/node_modules/react-native-store-version/dist/android.js
+++ b/node_modules/react-native-store-version/dist/android.js
@@ -8,7 +8,7 @@ export const getAndroidVersion = async (storeURL = '') => {
         }
         throw new Error('androidStoreURL is invalid.');
     });
-    const matches = response.match(/<span class="htlgb"><div class="IQ1z0d"><span class="htlgb">([0-9]+\.?[0-9]*\.?[0-9]*)<\/span><\/div><\/span>/);
+    const matches = response.match(/\[\[\[['"]((\d+\.)+\d+)['"]\]\],/);
     if (!matches) {
         throw new Error('can\'t get android app version.');
     }
_

Hope this help

**Comment by Zerolink2099** [comment] 2022-05-31 21:15
The error is caused by google play's new layout of the app`s page.


diff --git a/node_modules/react-native-store-version/dist/android.js b/node_modules/react-native-store-version/dist/android.js
index 469615f..ad10a8f 100644
--- a/node_modules/react-native-store-version/dist/android.js
+++ b/node_modules/react-native-store-version/dist/android.js
@@ -8,7 +8,7 @@ export const getAndroidVersion = async (storeURL = '') => {
         }
         throw new Error('androidStoreURL is invalid.');
     });
-    const matches = response.match(/<span class="htlgb"><div class="IQ1z0d"><span class="htlgb">([0-9]+\.?[0-9]*\.?[0-9]*)<\/span><\/div><\/span>/);
+    const matches = response.match(/\[\[\[['"]((\d+\.)+\d+)['"]\]\],/);
     if (!matches) {
         throw new Error('can\'t get android app version.');
     }

Hope this help

**Comment by Zerolink2099** [comment] 2022-05-31 21:18
The error is caused by google play's new layout of the app`s page. 

Update /node_modules/react-native-store-version/dist/android.js

line 11 from:

const matches = response.match(/<span class="htlgb"><div class="IQ1z0d"><span class="htlgb">([0-9]+\.?[0-9]*\.?[0-9]*)<\/span><\/div><\/span>/);

to:

const matches = response.match(/\[\[\[['"]((\d+\.)+\d+)['"]\]\],/);

Hope this help

**Comment by Zerolink2099** [comment] 2022-05-31 21:18
`const matches = response.match(/\[\[\[['"]((\d+\.)+\d+)['"]\]\],/);`

**Comment by LuckyMadu** [comment] 2022-06-07 09:52
> The error is caused by google play's new layout of the app`s page.
> 
> Update /node_modules/react-native-store-version/dist/android.js
> 
> line 11 from:
> 
> `const matches = response.match(/<span class="htlgb"><div class="IQ1z0d"><span class="htlgb">([0-9]+\.?[0-9]*\.?[0-9]*)<\/span><\/div><\/span>/);`
> 
> to:
> 
> `const matches = response.match(/\[\[\[['"]((\d+\.)+\d+)['"]\]\],/);`
> 
> Hope this help

This also not working for me!

**Comment by watanabeyu** [comment] 2022-06-09 04:33
related to https://github.com/watanabeyu/react-native-store-version/issues/39
I fix this error, sorry.

**Comment by leahaeussermann** [comment] 2022-06-20 07:57
Hey,
are there any news about the fix of the error? :) Will this be fixed any time soon? Cause I would like to use this for a project.

**Comment by jgudo** [comment] 2022-06-21 07:44
I'm also facing the issue and temporarily using the [patch-package](https://github.com/ds300/patch-package) until this issue gets resolved.

**Comment by watanabeyu** [comment] 2022-08-04 11:10
https://github.com/watanabeyu/react-native-store-version/pull/41

released new version, so close this issue.
Sorry for the long wait for an update.
thanks.

**Closed by watanabeyu** 2022-08-04 11:10 UTC
